blank_issues_enabled: false
contact_links:
  - name: Subscribe Mailing List
    url: mailto:user-subscribe@paimon.apache.org
    about: Subscribe User Mailing List
  - name: DingTalk Group (Chinese)
    url: https://qr.dingtalk.com/action/joingroup?code=v1,k1,+LzfVP12Bl5pdCtcy+G9YIDZjnXsKjhN/y3yLCQAffY=&_dt_no_comment=1&origin=11
    about: Join DingTalk Group
